openapi: 3.0.3
info:
  title: Collection API
  description: Collection API
  version: v1.0.0
security:
  - bearerAuth: []
tags:
  - name: Lists
paths:
  /v1.Lists/CreateList:
    post:
      tags:
        - Lists
      operationId: Lists_CreateList
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1.CreateListRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.CreateListResponse'
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/google.rpc.Status'
  /v1.Lists/CreateListStatus:
    post:
      tags:
        - Lists
      operationId: Lists_CreateListStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1.CreateListStatusRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.CreateListStatusResponse'
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/google.rpc.Status'
  /v1.Lists/GetList:
    post:
      tags:
        - Lists
      operationId: Lists_GetList
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1.GetListRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.List'
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/google.rpc.Status'
  /v1.Lists/UpdateList:
    post:
      tags:
        - Lists
      operationId: Lists_UpdateList
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1.UpdateListRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.UpdateListResponse'
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/google.rpc.Status'
  /v1.Lists/UpdateListStatus:
    post:
      tags:
        - Lists
      operationId: Lists_UpdateListStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1.UpdateListStatusRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.UpdateListStatusResponse'
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/google.rpc.Status'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    google.protobuf.Any:
      type: object
      properties:
        '@type':
          type: string
          description: The type of the serialized message.
      additionalProperties: true
      description: >-
        Contains an arbitrary serialized message along with a @type that
        describes the type of the serialized message.
    google.rpc.Status:
      type: object
      properties:
        code:
          type: integer
          description: >-
            The status code, which should be an enum value of
            [google.rpc.Code][google.rpc.Code].
          format: int32
        message:
          type: string
          description: >-
            A developer-facing error message, which should be in English. Any
            user-facing error message should be localized and sent in the
            [google.rpc.Status.details][google.rpc.Status.details] field, or
            localized by the client.
        details:
          type: array
          items:
            $ref: '#/components/schemas/google.protobuf.Any'
          description: >-
            A list of messages that carry the error details.  There is a common
            set of message types for APIs to use.
      description: >-
        The `Status` type defines a logical error model that is suitable for
        different programming environments, including REST APIs and RPC APIs. It
        is used by [gRPC](https://github.com/grpc). Each `Status` message
        contains three pieces of data: error code, error message, and error
        details. You can find out more about this error model and how to work
        with it in the [API Design
        Guide](https://cloud.google.com/apis/design/errors).
    v1.CreateListRequest:
      type: object
      properties:
        name:
          type: string
    v1.CreateListResponse:
      type: object
      properties:
        id:
          type: string
    v1.CreateListStatusRequest:
      type: object
      properties:
        listId:
          type: string
        name:
          type: string
    v1.CreateListStatusResponse:
      type: object
      properties:
        id:
          type: string
    v1.GetListRequest:
      type: object
      properties:
        id:
          type: string
    v1.List:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        statuses:
          type: array
          items:
            $ref: '#/components/schemas/v1.List_Status'
    v1.List_Status:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    v1.UpdateListRequest:
      type: object
      properties:
        id:
          type: string
        fields:
          type: array
          items:
            type: string
        name:
          type: string
        description:
          type: string
    v1.UpdateListResponse:
      type: object
      properties:
        id:
          type: string
    v1.UpdateListStatusRequest:
      type: object
      properties:
        id:
          type: string
        fields:
          type: array
          items:
            type: string
        name:
          type: string
    v1.UpdateListStatusResponse:
      type: object
      properties:
        id:
          type: string
